version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: milkyaway13/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    image: milkyaway13/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    image: milkyaway13/foodgram_nginx
    ports:
      - 8080:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend