# Generated by Django 3.2.16 on 2023-11-07 17:19

import django.core.validators
from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Укажите логин",
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Некорректные символы для логина",
                        regex="^[\\w.@+-]+\\Z",
                    ),
                    users.validators.validate_username,
                ],
                verbose_name="Логин",
            ),
        ),
    ]
