# Generated by Django 3.2.16 on 2023-11-15 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="subscriber",
            field=models.ForeignKey(
                help_text="Подписчик автора",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriber",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
